-- =============================================================================
-- Wheregüense — Migración 001: esquema inicial
-- =============================================================================
-- Basado en docs/diagrama_bd_v3.md (revisado y aprobado).
-- Motor: PostgreSQL 15 (Supabase).
--
-- Decisiones aplicadas en esta migración:
--   1. avatar_personaje usa el valor 'cabezon' (no 'enano').
--   2. qr_sello + sello.qr_sello_id quedan CREADAS pero sin conectar al flujo
--      de escaneo actual (funcionalidad futura).
--   3. negocio_horario guarda los 7 días; el formulario del front seguirá
--      enviando 2 franjas por ahora (ajuste de código posterior).
--
-- NO incluye:
--   - Políticas RLS  -> irán en 002_rls_policies.sql
--   - Datos semilla (sitios, insignias, niveles, piezas de avatar, rangos)
--                    -> irán en 003_seed.sql
--   - Triggers de integridad avanzada (ver notas "TODO trigger" más abajo)
--
-- Orden: extensiones -> helpers -> catálogos sin dependencias -> tablas hijas.
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- 0. Extensiones
-- -----------------------------------------------------------------------------
create extension if not exists "pgcrypto";   -- gen_random_uuid(), por si se usa


-- =============================================================================
-- 1. USUARIO
-- =============================================================================
-- Perfil de la app. La fila se crea 1:1 contra auth.users de Supabase Auth;
-- por eso el id NO se genera aquí, se copia del id de Auth (uuid).
-- Reemplaza: localStorage.perfilUsuario + avatarElegido + fotoPerfil.
create table usuario (
    id                  uuid        primary key
                                    references auth.users (id) on delete cascade,
    nombre_usuario      text        not null,
    email               text        not null unique,
    rol                 text        not null default 'turista'
                                    check (rol in ('turista', 'emprendedor', 'admin')),
    pais                text,
    idioma_preferido    text        not null default 'es',
    avatar_personaje    text        not null default 'cabezon'
                                    check (avatar_personaje in ('cabezon', 'gigantona')),
    foto_perfil_url     text,
    fecha_registro      timestamptz not null default now()
);

comment on table  usuario is 'Perfil de usuario, 1:1 con auth.users. id = auth.users.id.';
comment on column usuario.avatar_personaje is 'Personaje base elegido en SeleccionDanzante. Distinto de la categoría de avatar "gigantona".';


-- =============================================================================
-- 2. NIVEL  (catálogo de configuración)
-- =============================================================================
-- Curva numérica de niveles 1..40 (umbrales acumulados de sellos).
-- Reemplaza el cálculo fijo de generarUmbrales()/UMBRALES_NIVEL en utils/rango.js.
-- El nivel actual de un usuario se DERIVA por consulta (count de sellos), no se guarda.
create table nivel (
    numero              smallint    primary key check (numero between 1 and 40),
    sellos_necesarios   integer     not null unique check (sellos_necesarios >= 0)
);

comment on table nivel is 'Config: umbral de sellos para cada nivel 1..40. Editable sin redesplegar.';


-- =============================================================================
-- 3. RANGO  (catálogo de configuración)
-- =============================================================================
-- Los 3 escalones con nombre y color (Principiante / Explorador / Maestro Güegüense).
-- Reemplaza obtenerRango() en utils/rango.js. Coexiste con NIVEL (son sistemas distintos).
create table rango (
    id                  integer     generated by default as identity primary key,
    nombre              text        not null unique,
    sellos_necesarios   integer     not null unique check (sellos_necesarios >= 0),
    beneficio           text,
    color               text        not null check (color ~ '^#[0-9A-Fa-f]{6}$')
);

comment on table rango is 'Config: escalón de rango nombrado según cantidad de sellos.';


-- =============================================================================
-- 4. RUTA
-- =============================================================================
-- Reemplaza data/rutas.js (hoy una sola ruta con los sitios embebidos).
create table ruta (
    id                  integer     generated by default as identity primary key,
    nombre              text        not null,
    ciudad              text        not null
);

comment on table ruta is 'Ruta turística (p. ej. "Ruta Dariana").';


-- =============================================================================
-- 5. INSIGNIA
-- =============================================================================
-- Reemplaza el mapa INSIGNIAS de data/insignias.js (slug -> PNG) y sitio.badge.
-- 1:1 con SITIO (ver sitio.insignia_id UNIQUE).
create table insignia (
    id                  integer     generated by default as identity primary key,
    clave               text        not null unique,
    nombre              text        not null,
    imagen_url          text        not null
);

comment on table  insignia is 'Insignia que se gana al sellar un sitio. Una por sitio.';
comment on column insignia.clave is 'Slug estable: cathedral, territory, guitar, ... (= sitio.badge del código).';


-- =============================================================================
-- 6. CATEGORIA_AVATAR
-- =============================================================================
-- Los 4 slots de personalización de avatar (rostro / ropa / sombrero / gigantona).
-- Reemplaza la estructura de data/avatarPiezas.js (ROSTROS, ROPAS, SOMBREROS, GIGANTONA).
create table categoria_avatar (
    id                  integer     generated by default as identity primary key,
    clave               text        not null unique
                                    check (clave in ('rostro', 'ropa', 'sombrero', 'gigantona')),
    nombre              text        not null,
    obligatoria         boolean     not null default true
);

comment on column categoria_avatar.obligatoria is 'sombrero = false (arranca vacío); rostro/ropa/gigantona = true.';


-- =============================================================================
-- 7. SITIO
-- =============================================================================
-- Reemplaza data/sitios.js. name->nombre, desc->descripcion_corta,
-- position:[lat,lng]->latitud/longitud, badge->FK insignia_id.
create table sitio (
    id                  integer     generated by default as identity primary key,
    insignia_id         integer     not null unique references insignia (id) on delete restrict,
    nombre              text        not null,
    descripcion_corta   text        not null,
    historia            text,
    latitud             double precision not null,
    longitud            double precision not null,
    imagen_url          text
);

comment on table  sitio is 'Punto cultural del mapa.';
comment on column sitio.insignia_id is 'UNIQUE => relación 1:1 con insignia.';


-- =============================================================================
-- 8. PIEZA_AVATAR
-- =============================================================================
-- Reemplaza los mapas id->PNG de data/avatarPiezas.js (rostro_1, ropa_3, ...).
create table pieza_avatar (
    id                  integer     generated by default as identity primary key,
    categoria_id        integer     not null references categoria_avatar (id) on delete restrict,
    clave               text        not null unique,
    imagen_url          text        not null,
    es_inicial          boolean     not null default false,
    -- permite FK compuesta (pieza_id, categoria_id) desde avatar_equipado
    unique (id, categoria_id)
);

comment on column pieza_avatar.es_inicial is 'true para las piezas por defecto (rostro_1, ropa_1, gigantona_1).';


-- =============================================================================
-- 9. RUTA_SITIO  (puente N:M con orden)
-- =============================================================================
-- Sin cambios respecto a v2. Permite que un sitio esté en varias rutas.
create table ruta_sitio (
    ruta_id             integer     not null references ruta (id) on delete cascade,
    sitio_id            integer     not null references sitio (id) on delete cascade,
    orden               smallint    not null default 0,
    primary key (ruta_id, sitio_id)
);

comment on table ruta_sitio is 'Qué sitios componen cada ruta y en qué orden.';


-- =============================================================================
-- 10. RUTA_GUARDADA  (puente N:M usuario-ruta)
-- =============================================================================
-- Reemplaza localStorage.rutasGuardadas de useRutasGuardadas.js (favoritos).
create table ruta_guardada (
    usuario_id          uuid        not null references usuario (id) on delete cascade,
    ruta_id             integer     not null references ruta (id) on delete cascade,
    fecha_guardado      timestamptz not null default now(),
    primary key (usuario_id, ruta_id)
);

comment on table ruta_guardada is 'Rutas marcadas como guardadas/favoritas por el usuario.';


-- =============================================================================
-- 11. NEGOCIO
-- =============================================================================
-- Reemplaza localStorage.negocio de useNegocio.js. Añade responsable, cedula_ruc,
-- telefono, descripcion, fecha_envio y los campos de suscripción de v2.
-- fotos/productos/horarios/qr salen a tablas propias.
create table negocio (
    id                              integer     generated by default as identity primary key,
    usuario_id                      uuid        not null references usuario (id) on delete cascade,
    nombre_negocio                  text        not null,
    categoria                       text        not null,
    responsable                     text,
    cedula_ruc                      text,
    telefono                        text,
    latitud                         double precision not null,
    longitud                        double precision not null,
    descripcion                     text,
    estado                          text        not null default 'pendiente'
                                                check (estado in ('pendiente', 'activo', 'rechazado')),
    motivo_rechazo                  text,
    fecha_envio                     timestamptz not null default now(),
    fecha_aprobacion                timestamptz,
    fecha_vencimiento_suscripcion   timestamptz,
    suscripcion_activa              boolean     not null default false,
    -- solo puede haber motivo_rechazo si el estado es 'rechazado'
    constraint negocio_motivo_solo_si_rechazado
        check (motivo_rechazo is null or estado = 'rechazado')
);

comment on table negocio is 'Negocio registrado por un emprendedor. Estado de aprobación embebido.';


-- =============================================================================
-- 12. EVENTO
-- =============================================================================
-- Reemplaza data/eventos.js. sitioRelacionado (string con el nombre) pasa a FK.
create table evento (
    id                      integer     generated by default as identity primary key,
    sitio_relacionado_id    integer     references sitio (id) on delete set null,
    negocio_organizador_id  integer     references negocio (id) on delete set null,
    nombre                  text        not null,
    fecha_inicio            date        not null,
    fecha_fin               date        not null,
    ubicacion               text        not null,
    descripcion             text,
    constraint evento_fechas_coherentes check (fecha_fin >= fecha_inicio)
);

comment on column evento.ubicacion is 'Etiqueta libre de ubicación. sitio_relacionado_id es opcional además de esto.';


-- =============================================================================
-- 13. PIEZA_DESBLOQUEADA
-- =============================================================================
-- Reemplaza localStorage.avatarDesbloqueos. Qué piezas posee el usuario.
create table pieza_desbloqueada (
    usuario_id          uuid        not null references usuario (id) on delete cascade,
    pieza_id            integer     not null references pieza_avatar (id) on delete cascade,
    nivel_hito          smallint    check (nivel_hito is null or (nivel_hito >= 5 and nivel_hito % 5 = 0)),
    fecha_desbloqueo    timestamptz not null default now(),
    primary key (usuario_id, pieza_id)
);

comment on column pieza_desbloqueada.nivel_hito is 'Hito (nivel múltiplo de 5) que concedió la pieza. NULL = pieza inicial.';


-- =============================================================================
-- 14. AVATAR_EQUIPADO
-- =============================================================================
-- Reemplaza localStorage.avatarSeleccion. Una pieza equipada por categoría.
-- La PK (usuario_id, categoria_id) garantiza "una por slot".
create table avatar_equipado (
    usuario_id          uuid        not null references usuario (id) on delete cascade,
    categoria_id        integer     not null references categoria_avatar (id) on delete cascade,
    pieza_id            integer     references pieza_avatar (id) on delete set null,
    primary key (usuario_id, categoria_id),
    -- la pieza equipada debe pertenecer a esa categoría
    constraint avatar_equipado_pieza_de_la_categoria
        foreign key (pieza_id, categoria_id) references pieza_avatar (id, categoria_id)
);

comment on column avatar_equipado.pieza_id is 'NULL permitido (sombrero sin equipar). TODO trigger: exigir que esté en pieza_desbloqueada del usuario.';


-- =============================================================================
-- 15. USUARIO_HITO
-- =============================================================================
-- Reemplaza localStorage.avatarMilestonesResueltos + la parte "milestone/estado"
-- de avatarCandidatosPendientes. Un hito por cada nivel múltiplo de 5 alcanzado.
create table usuario_hito (
    usuario_id          uuid        not null references usuario (id) on delete cascade,
    nivel_hito          smallint    not null check (nivel_hito >= 5 and nivel_hito % 5 = 0),
    pieza_elegida_id    integer     references pieza_avatar (id) on delete restrict,
    fecha_generado      timestamptz not null default now(),
    fecha_resuelto      timestamptz,
    primary key (usuario_id, nivel_hito),
    -- "resuelto" <=> hay pieza elegida
    constraint usuario_hito_resuelto_coherente
        check ((pieza_elegida_id is null) = (fecha_resuelto is null))
);

comment on table usuario_hito is 'Hito de desbloqueo de avatar. pieza_elegida_id NULL = pendiente de elegir.';


-- =============================================================================
-- 16. QR_SELLO
-- =============================================================================
-- Reemplaza el objeto embebido negocio.qr ({token,color,fecha}) de GenerarQR.jsx.
-- CREADA pero aún NO conectada al flujo de escaneo (decisión 2). canjes_actuales
-- NO se guarda: es count(sello where qr_sello_id = ...).
create table qr_sello (
    id                  integer     generated by default as identity primary key,
    negocio_id          integer     not null references negocio (id) on delete cascade,
    token               text        not null unique,
    nombre_actividad    text        not null,
    color               text        not null default '#1119BC'
                                    check (color ~ '^#[0-9A-Fa-f]{6}$'),
    fecha_creacion      timestamptz not null default now(),
    fecha_expiracion    timestamptz,
    limite_canjes       integer     check (limite_canjes is null or limite_canjes > 0)
);

comment on column qr_sello.limite_canjes is 'NULL = sin límite. El conteo actual se calcula por consulta, no se almacena.';


-- =============================================================================
-- 17. NEGOCIO_FOTO
-- =============================================================================
-- Reemplaza el fotos[] de v2 (violaba 1NF) y el cantidadFotos de useNegocio.js.
-- El mínimo de 3 fotos se valida en la app (RegistroNegocio.jsx).
create table negocio_foto (
    id                  integer     generated by default as identity primary key,
    negocio_id          integer     not null references negocio (id) on delete cascade,
    url                 text        not null,
    tipo                text        not null default 'exterior'
                                    check (tipo in ('exterior', 'interior', 'producto')),
    orden               smallint    not null default 0
);

comment on table negocio_foto is 'Fotos del negocio (exterior / interior / producto).';


-- =============================================================================
-- 18. NEGOCIO_HORARIO
-- =============================================================================
-- Reemplaza negocio.horarios. Guarda los 7 días (decisión 3); el formulario
-- del front por ahora solo manda 2 franjas y el backend las expande.
create table negocio_horario (
    negocio_id          integer     not null references negocio (id) on delete cascade,
    dia_semana          smallint    not null check (dia_semana between 0 and 6),
    hora_apertura       time,
    hora_cierre         time,
    cerrado             boolean     not null default false,
    primary key (negocio_id, dia_semana),
    -- si está cerrado no hay horas; si está abierto, ambas horas son obligatorias
    constraint negocio_horario_coherente check (
        (cerrado and hora_apertura is null and hora_cierre is null)
        or (not cerrado and hora_apertura is not null and hora_cierre is not null)
    )
);

comment on column negocio_horario.dia_semana is '0 = domingo ... 6 = sábado.';


-- =============================================================================
-- 19. PRODUCTO
-- =============================================================================
-- Reemplaza el array negocio.productos ([{id,nombre}]) de useNegocio.js.
create table producto (
    id                  integer     generated by default as identity primary key,
    negocio_id          integer     not null references negocio (id) on delete cascade,
    nombre              text        not null,
    orden               smallint    not null default 0
);

comment on table producto is 'Producto / ítem de menú listado en el perfil del negocio.';


-- =============================================================================
-- 20. HITO_CANDIDATO
-- =============================================================================
-- Reemplaza el array "opciones" de avatarCandidatosPendientes: las 3 piezas al
-- azar ofrecidas para un hito (elegirCandidatosAlAzar()).
-- Cantidad exacta = 3 se valida en la app (CANTIDAD_CANDIDATOS).
create table hito_candidato (
    usuario_id          uuid        not null,
    nivel_hito          smallint    not null,
    pieza_id            integer     not null references pieza_avatar (id) on delete cascade,
    primary key (usuario_id, nivel_hito, pieza_id),
    foreign key (usuario_id, nivel_hito)
        references usuario_hito (usuario_id, nivel_hito) on delete cascade
);

comment on table hito_candidato is 'Las 3 piezas candidatas ofrecidas al usuario para un hito concreto.';


-- =============================================================================
-- 21. SELLO
-- =============================================================================
-- Reemplaza el array localStorage.sellos de useSellos.js. Se quita el campo
-- denormalizado "nombre" (dependía de sitio_id -> violaba 3NF).
create table sello (
    id                  bigint      generated by default as identity primary key,
    usuario_id          uuid        not null references usuario (id) on delete cascade,
    sitio_id            integer     references sitio (id) on delete restrict,
    qr_sello_id         integer     references qr_sello (id) on delete restrict,
    tipo                text        not null check (tipo in ('geolocalizacion', 'qr')),
    fecha_sello         timestamptz not null default now(),
    -- no se puede sellar dos veces el mismo sitio (hoy lo valida useSellos.sellar())
    constraint sello_unico_por_sitio unique (usuario_id, sitio_id),
    -- exactamente un origen, coherente con el tipo
    constraint sello_origen_valido check (
        (tipo = 'geolocalizacion' and sitio_id is not null and qr_sello_id is null)
        or (tipo = 'qr' and qr_sello_id is not null and sitio_id is null)
    )
);

comment on table  sello is 'Sello obtenido por el usuario. Origen: geolocalización (sitio) o QR de negocio (futuro).';
comment on column sello.qr_sello_id is 'Reservado para el flujo de QR de negocio; hoy siempre NULL.';


-- =============================================================================
-- 22. FK circular: usuario_hito.pieza_elegida_id debe ser un candidato del hito
-- =============================================================================
-- Se añade después porque hito_candidato depende de usuario_hito y viceversa.
-- MATCH SIMPLE: si pieza_elegida_id es NULL, no se valida (hito pendiente).
alter table usuario_hito
    add constraint usuario_hito_pieza_es_candidata
    foreign key (usuario_id, nivel_hito, pieza_elegida_id)
    references hito_candidato (usuario_id, nivel_hito, pieza_id)
    on delete restrict;


-- -----------------------------------------------------------------------------
-- Índices de apoyo para FKs consultadas con frecuencia
-- -----------------------------------------------------------------------------
create index idx_sello_usuario           on sello (usuario_id);
create index idx_sello_sitio             on sello (sitio_id);
create index idx_sello_qr                on sello (qr_sello_id);
create index idx_negocio_usuario         on negocio (usuario_id);
create index idx_negocio_estado          on negocio (estado);
create index idx_qr_sello_negocio        on qr_sello (negocio_id);
create index idx_ruta_sitio_sitio        on ruta_sitio (sitio_id);
create index idx_ruta_guardada_ruta      on ruta_guardada (ruta_id);
create index idx_evento_sitio            on evento (sitio_relacionado_id);
create index idx_evento_negocio          on evento (negocio_organizador_id);
create index idx_pieza_desbloqueada_pieza on pieza_desbloqueada (pieza_id);
create index idx_avatar_equipado_pieza   on avatar_equipado (pieza_id);
create index idx_pieza_avatar_categoria  on pieza_avatar (categoria_id);


-- =============================================================================
-- Notas para migraciones siguientes
-- =============================================================================
-- 002_rls_policies.sql  -> enable row level security + políticas por auth.uid()
--                          (usuario: su fila; sello/ruta_guardada/pieza_*/avatar_*/
--                           usuario_hito/hito_candidato: filtrado por dueño;
--                           negocio y tablas hijas: dueño + rol admin;
--                           catálogos: lectura pública, escritura service_role).
-- 003_seed.sql          -> nivel (curva 0,2,3,5,8,13,21,...), rango (3 escalones),
--                          insignia (10 slugs), sitio (10), categoria_avatar (4),
--                          pieza_avatar (rostro_1..5, ropa_1..7, sombrero_1..6,
--                          gigantona_1..5), ruta "Ruta Dariana" + ruta_sitio,
--                          evento (4).
--
-- TODO triggers (integridad que no cabe en CHECK/FK):
--   - avatar_equipado.pieza_id debe existir en pieza_desbloqueada del mismo usuario.
--   - hito_candidato: exactamente 3 filas por (usuario_id, nivel_hito).
--   - al resolver usuario_hito: insertar automáticamente en pieza_desbloqueada.

commit;
