-- docs/migrations/011_expansion_ruta_completa.sql
--
-- Expande la Ruta Dariana de 10 a 60 sitios que otorgan sello:
-- 49 sitios extraídos de src/data/sitios.js (27 con su position tal cual,
-- ya de alta precisión; 22 con coordenadas verificadas contra Google Maps
-- en esta sesión, que reemplazan la de sitios.js) + Puerto Salvador Allende
-- (Managua), agregado fuera de la lista original como sitio de prueba para
-- el hackathon. Quedan fuera, sin tocar: ids 32,33,34,37,42,43,63,83,97
-- (no verificables aún; se ven en otra sesión).
--
-- insignia.nombre para los 49 nuevos (y para Puerto Salvador Allende): se usó
-- el mismo sitio.nombre completo (no un nombre genérico de icono como los 10
-- originales -- cathedral/territory/guitar/etc. -- porque cada badge nuevo es
-- un slug específico del sitio, no un arquetipo reutilizable). Puerto
-- Salvador Allende tiene insignia propia 'puerto_salvador_allende' (ya no
-- reutiliza la clave 'territory' de Ruinas de León Viejo como placeholder).

begin;

-- 1. Insignias nuevas para los 49 sitios extraídos de sitios.js
insert into public.insignia (clave, nombre, imagen_url) values
  ('casa_museo_y_archivo_ruben_dario', 'Casa Museo y Archivo Rubén Darío', 'badges/casa_museo_y_archivo_ruben_dario_transparent.png'),
  ('estatua_de_ruben_dario_colegio_la_salle', 'Estatua de Rubén Darío - Colegio La Salle', 'badges/estatua_de_ruben_dario_colegio_la_salle_transparent.png'),
  ('hotel_el_convento_antiguo_lugar', 'Hotel El Convento / antiguo lugar vinculado a su infancia', 'badges/hotel_el_convento_antiguo_lugar_transparent.png'),
  ('parque_de_los_poetas', 'Parque de los Poetas', 'badges/parque_de_los_poetas_transparent.png'),
  ('antigua_casa_de_salud_debayle', 'Antigua Casa de Salud Debayle', 'badges/antigua_casa_de_salud_debayle_transparent.png'),
  ('plazoleta_ruben_dario', 'Plazoleta Rubén Darío', 'badges/plazoleta_ruben_dario_transparent.png'),
  ('parque_centenario_ruben_dario', 'Parque Centenario Rubén Darío', 'badges/parque_centenario_ruben_dario_transparent.png'),
  ('iglesia_la_merced', 'Iglesia La Merced', 'badges/iglesia_la_merced_transparent.png'),
  ('iglesia_el_calvario', 'Iglesia El Calvario', 'badges/iglesia_el_calvario_transparent.png'),
  ('museo_casa_natal_rigoberto_lopez_perez', 'Museo Casa Natal Rigoberto López Pérez', 'badges/museo_casa_natal_rigoberto_lopez_perez_transparent.png'),
  ('centro_cultural_y_museo_rigoberto_lopez', 'Centro Cultural y Museo Rigoberto López Pérez', 'badges/centro_cultural_y_museo_rigoberto_lopez_transparent.png'),
  ('museo_de_leyendas_y_tradiciones_coronel', 'Museo de Leyendas y Tradiciones Coronel Joaquín de Arrechavala', 'badges/museo_de_leyendas_y_tradiciones_coronel_transparent.png'),
  ('museo_entomologico', 'Museo Entomológico', 'badges/museo_entomologico_transparent.png'),
  ('centro_de_arte_fundacion_ortiz_gurdian', 'Centro de Arte Fundación Ortiz-Gurdián', 'badges/centro_de_arte_fundacion_ortiz_gurdian_transparent.png'),
  ('centro_cultural_ruben_dario', 'Centro Cultural Rubén Darío', 'badges/centro_cultural_ruben_dario_transparent.png'),
  ('mercadito_de_sutiaba_como_espacio', 'Mercadito de Sutiaba como espacio cultural y tradicional', 'badges/mercadito_de_sutiaba_como_espacio_transparent.png'),
  ('muralismo_historico_de_leon', 'Muralismo histórico de León', 'badges/muralismo_historico_de_leon_transparent.png'),
  ('alcaldia_municipal_de_leon_edificio', 'Alcaldía Municipal de León / Edificio Central Marcos Somarriba', 'badges/alcaldia_municipal_de_leon_edificio_transparent.png'),
  ('palacio_municipal_hoy_museo_de_la', 'Palacio Municipal, hoy Museo de la Insurrección', 'badges/palacio_municipal_hoy_museo_de_la_transparent.png'),
  ('antigua_estacion_del_ferrocarril', 'Antigua Estación del Ferrocarril', 'badges/antigua_estacion_del_ferrocarril_transparent.png'),
  ('casa_de_la_familia_lacayo_hotel_la_perla', 'Casa de la Familia Lacayo / Hotel La Perla', 'badges/casa_de_la_familia_lacayo_hotel_la_perla_transparent.png'),
  ('conjunto_de_las_cuatro_esquinas', 'Conjunto de las Cuatro Esquinas', 'badges/conjunto_de_las_cuatro_esquinas_transparent.png'),
  ('casa_buzon_de_los_bervis', 'Casa Buzón de los Bervis', 'badges/casa_buzon_de_los_bervis_transparent.png'),
  ('monumento_donde_cayo_luisa_amanda', 'Monumento donde cayó Luisa Amanda Espinoza y Enrique Lorente', 'badges/monumento_donde_cayo_luisa_amanda_transparent.png'),
  ('placa_a_los_heroes_y_martires_de', 'Placa a los Héroes y Mártires de Veracruz', 'badges/placa_a_los_heroes_y_martires_de_transparent.png'),
  ('placa_de_la_iglesia_el_calvario', 'Placa de la Iglesia El Calvario vinculada a los hechos de la insurrección', 'badges/placa_de_la_iglesia_el_calvario_transparent.png'),
  ('reparto_veracruz_sitio_historico_de_los', 'Reparto Veracruz / sitio histórico de los Héroes de Veracruz', 'badges/reparto_veracruz_sitio_historico_de_los_transparent.png'),
  ('iglesia_san_francisco_de_asis', 'Iglesia San Francisco de Asís', 'badges/iglesia_san_francisco_de_asis_transparent.png'),
  ('iglesia_san_juan_bautista_de_sutiaba', 'Iglesia San Juan Bautista de Sutiaba', 'badges/iglesia_san_juan_bautista_de_sutiaba_transparent.png'),
  ('iglesia_san_juan_de_dios', 'Iglesia San Juan de Dios', 'badges/iglesia_san_juan_de_dios_transparent.png'),
  ('iglesia_san_felipe_apostol', 'Iglesia San Felipe Apóstol', 'badges/iglesia_san_felipe_apostol_transparent.png'),
  ('santuario_nuestra_senora_de_guadalupe', 'Santuario Nuestra Señora de Guadalupe', 'badges/santuario_nuestra_senora_de_guadalupe_transparent.png'),
  ('iglesia_san_nicolas_de_tolentino_del', 'Iglesia San Nicolás de Tolentino del Laborío', 'badges/iglesia_san_nicolas_de_tolentino_del_transparent.png'),
  ('iglesia_nuestra_senora_del_pilar_de', 'Iglesia Nuestra Señora del Pilar de Zaragoza', 'badges/iglesia_nuestra_senora_del_pilar_de_transparent.png'),
  ('iglesia_san_isidro_labrador', 'Iglesia San Isidro Labrador', 'badges/iglesia_san_isidro_labrador_transparent.png'),
  ('ruinas_de_ermita_san_sebastian_sutiaba', 'Ruinas de Ermita San Sebastián, Sutiaba', 'badges/ruinas_de_ermita_san_sebastian_sutiaba_transparent.png'),
  ('centro_sociocultural_de_sutiaba_marina', 'Centro Sociocultural de Sutiaba Marina Maradiaga', 'badges/centro_sociocultural_de_sutiaba_marina_transparent.png'),
  ('museo_de_arte_sacro_monsenor_cesar', 'Museo de Arte Sacro Monseñor César Bosco Vivas Robelo', 'badges/museo_de_arte_sacro_monsenor_cesar_transparent.png'),
  ('biblioteca_publica_ruben_dario', 'Biblioteca Pública Rubén Darío', 'badges/biblioteca_publica_ruben_dario_transparent.png'),
  ('colegio_tridentino_san_ramon', 'Colegio Tridentino San Ramón', 'badges/colegio_tridentino_san_ramon_transparent.png'),
  ('palacio_episcopal', 'Palacio Episcopal', 'badges/palacio_episcopal_transparent.png'),
  ('inmueble_de_la_facultad_de_derecho_de', 'Inmueble de la Facultad de Derecho de la UNAN-León', 'badges/inmueble_de_la_facultad_de_derecho_de_transparent.png'),
  ('hospital_escuela_oscar_danilo_rosales', 'Hospital Escuela Oscar Danilo Rosales (HEODRA)', 'badges/hospital_escuela_oscar_danilo_rosales_transparent.png'),
  ('puente_de_guadalupe', 'Puente de Guadalupe', 'badges/puente_de_guadalupe_transparent.png'),
  ('fortin_de_acosasco', 'Fortín de Acosasco', 'badges/fortin_de_acosasco_transparent.png'),
  ('mausoleo_a_los_heroes_y_martires_de_la', 'Mausoleo a los Héroes y Mártires de la Revolución', 'badges/mausoleo_a_los_heroes_y_martires_de_la_transparent.png'),
  ('galeria_heroes_y_martires_de_leon', 'Galería Héroes y Mártires de León', 'badges/galeria_heroes_y_martires_de_leon_transparent.png'),
  ('cancha_espacio_historico_23_de_julio', 'Cancha / espacio histórico 23 de Julio', 'badges/cancha_espacio_historico_23_de_julio_transparent.png'),
  ('cementerio_de_guadalupe', 'Cementerio de Guadalupe', 'badges/cementerio_de_guadalupe_transparent.png'),
  ('puerto_salvador_allende', 'Puerto Salvador Allende', 'badges/puerto_salvador_allende_transparent.png');

-- 2. Sitios nuevos (49), resolviendo insignia_id por join a la clave recién
--    insertada (evita RETURNING/variables para 49 filas).
insert into public.sitio (id, insignia_id, nombre, descripcion_corta, historia, latitud, longitud, radio_sello_metros)
select v.id, i.id, v.nombre, v.descripcion_corta, v.historia, v.latitud, v.longitud, v.radio_sello_metros
from (values
  (11, 'casa_museo_y_archivo_ruben_dario', 'Casa Museo y Archivo Rubén Darío', 'Casa de infancia del poeta; hoy museo y archivo.', 'Casa Museo y Archivo Rubén Darío es la parada principal del circuito dariano en León y ocupa la casa solariega conocida como Las Cuatro Esquinas, donde Félix Rubén García Sarmiento vivió desde sus primeros días de vida hasta los 14 años. El museo fue creado por iniciativa del doctor Edgardo Buitrago e inaugurado en 1964; conserva espacios de la vivienda, objetos personales, documentos, manuscritos y una biblioteca especializada que permite reconstruir la infancia, formación y trayectoria del poeta. La importancia del lugar no depende únicamente de su relación con Darío: también muestra cómo era una casa leonesa de tradición colonial y cómo la arquitectura doméstica se convirtió en patrimonio cultural. Por ello funciona a la vez como museo literario, archivo histórico y punto de partida para comprender la identidad de León como ciudad de poetas. Casa de infancia del poeta; hoy museo y archivo.', 12.434871, -86.882862, 30),
  (12, 'estatua_de_ruben_dario_colegio_la_salle', 'Estatua de Rubén Darío - Colegio La Salle', 'Hito escultórico de la ruta relacionado con la memoria pública de Darío.', 'Estatua de Rubén Darío - Colegio La Salle es un punto de interés dentro del patrimonio leonés. Dentro del circuito dariano de León, este sitio adquiere valor por su relación directa o simbólica con la vida, educación, obra y memoria pública de Rubén Darío. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Hito escultórico de la ruta relacionado con la memoria pública de Darío.', 12.435439, -86.883345, 30),
  (14, 'hotel_el_convento_antiguo_lugar', 'Hotel El Convento / antiguo lugar vinculado a su infancia', 'Lugar relacionado con la formación y vida temprana del poeta.', 'Hotel El Convento / antiguo lugar vinculado a su infancia es un punto de interés dentro del patrimonio leonés. Dentro del circuito dariano de León, este sitio adquiere valor por su relación directa o simbólica con la vida, educación, obra y memoria pública de Rubén Darío. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Lugar relacionado con la formación y vida temprana del poeta.', 12.435732, -86.88164, 30),
  (16, 'parque_de_los_poetas', 'Parque de los Poetas', 'Espacio dedicado a la tradición literaria leonesa.', 'Parque de los Poetas es un punto de interés dentro del patrimonio leonés. Dentro del circuito dariano de León, este sitio adquiere valor por su relación directa o simbólica con la vida, educación, obra y memoria pública de Rubén Darío. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Espacio dedicado a la tradición literaria leonesa.', 12.437448, -86.880622, 30),
  (19, 'antigua_casa_de_salud_debayle', 'Antigua Casa de Salud Debayle', 'Debayle y a la vida intelectual de León.', 'Antigua Casa de Salud Debayle es un punto de interés dentro del patrimonio leonés. Dentro del circuito dariano de León, este sitio adquiere valor por su relación directa o simbólica con la vida, educación, obra y memoria pública de Rubén Darío. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Inmueble histórico vinculado al doctor Luis H. Debayle y a la vida intelectual de León.', 12.43416, -86.877396, 30),
  (21, 'plazoleta_ruben_dario', 'Plazoleta Rubén Darío', 'Espacio urbano con monumento al poeta en el Paseo de los Leones.', 'Plazoleta Rubén Darío es un punto de interés dentro del patrimonio leonés. Dentro del circuito dariano de León, este sitio adquiere valor por su relación directa o simbólica con la vida, educación, obra y memoria pública de Rubén Darío. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Espacio urbano con monumento al poeta en el Paseo de los Leones.', 12.422548, -86.872952, 80),
  (22, 'parque_centenario_ruben_dario', 'Parque Centenario Rubén Darío', 'Parque creado en 2016 para conmemorar el centenario de la muerte de Darío.', 'Parque Centenario Rubén Darío es un punto de interés dentro del patrimonio leonés. Dentro del circuito dariano de León, este sitio adquiere valor por su relación directa o simbólica con la vida, educación, obra y memoria pública de Rubén Darío. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Parque creado en 2016 para conmemorar el centenario de la muerte de Darío.', 12.417755, -86.869637, 80),
  (23, 'iglesia_la_merced', 'Iglesia La Merced', 'Santuario histórico y una de las fachadas más reconocibles de León.', 'Iglesia La Merced es un punto de interés dentro del patrimonio leonés. En el conjunto religioso de León, este templo o ruina forma parte del paisaje que hizo de la ciudad un referente del patrimonio colonial y de la tradición religiosa nicaragüense. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Santuario histórico y una de las fachadas más reconocibles de León.', 12.436486, -86.878989, 30),
  (24, 'iglesia_el_calvario', 'Iglesia El Calvario', 'Templo histórico de marcada presencia urbana y vínculo con la memoria de la ciudad.', 'Iglesia El Calvario es un punto de interés dentro del patrimonio leonés. En el conjunto religioso de León, este templo o ruina forma parte del paisaje que hizo de la ciudad un referente del patrimonio colonial y de la tradición religiosa nicaragüense. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Templo histórico de marcada presencia urbana y vínculo con la memoria de la ciudad.', 12.43179, -86.872782, 30),
  (45, 'museo_casa_natal_rigoberto_lopez_perez', 'Museo Casa Natal Rigoberto López Pérez', 'Casa natal y espacio de memoria del poeta y figura histórica de la ciudad.', 'Museo Casa Natal Rigoberto López Pérez es un punto de interés dentro del patrimonio leonés. Como espacio de memoria, investigación, exhibición o educación, este lugar contribuye a explicar la identidad histórica y cultural de León y de sus comunidades. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Casa natal y espacio de memoria del poeta y figura histórica de la ciudad.', 12.436139, -86.872808, 80),
  (46, 'centro_cultural_y_museo_rigoberto_lopez', 'Centro Cultural y Museo Rigoberto López Pérez', 'Antigua Casa del Obrero, hoy espacio museístico relacionado con la historia política de Nicaragua.', 'Centro Cultural y Museo Rigoberto López Pérez es un punto de interés dentro del patrimonio leonés. Como espacio de memoria, investigación, exhibición o educación, este lugar contribuye a explicar la identidad histórica y cultural de León y de sus comunidades. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Antigua Casa del Obrero, hoy espacio museístico relacionado con la historia política de Nicaragua.', 12.436583, -86.880774, 30),
  (47, 'museo_de_leyendas_y_tradiciones_coronel', 'Museo de Leyendas y Tradiciones Coronel Joaquín de Arrechavala', 'Museo instalado en el antiguo edificio de la cárcel conocida como La 21.', 'El Museo de Leyendas y Tradiciones Coronel Joaquín de Arrechavala ocupa el edificio de la antigua cárcel conocida como «La 21», un inmueble que adquirió un valor simbólico especialmente fuerte por los usos represivos que tuvo durante el siglo XX. El museo transforma ese pasado en un espacio de interpretación de las leyendas, tradiciones y personajes de León, y al mismo tiempo conserva la memoria física del edificio y de la historia política que lo rodea. Las salas presentan relatos y elementos de la cultura popular, mientras algunas áreas explican las condiciones y formas de tortura asociadas al antiguo presidio. Su interés turístico está, precisamente, en esa doble lectura: por un lado, patrimonio material de la ciudad y, por otro, memoria social. Es uno de los lugares donde la cultura oral, la historia política y la arquitectura histórica se encuentran en un mismo recorrido. Museo instalado en el antiguo edificio de la cárcel conocida como La 21.', 12.432011, -86.878846, 80),
  (48, 'museo_entomologico', 'Museo Entomológico', 'Colección científica y educativa que forma parte del patrimonio cultural y académico de León.', 'Museo Entomológico es un punto de interés dentro del patrimonio leonés. Como espacio de memoria, investigación, exhibición o educación, este lugar contribuye a explicar la identidad histórica y cultural de León y de sus comunidades. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Colección científica y educativa que forma parte del patrimonio cultural y académico de León.', 12.434754, -86.871226, 80),
  (49, 'centro_de_arte_fundacion_ortiz_gurdian', 'Centro de Arte Fundación Ortiz-Gurdián', 'Conjunto de casas patrimoniales convertido en importante espacio de arte y cultura.', 'El Centro de Arte Fundación Ortiz-Gurdián ocupa varias casas patrimoniales del centro histórico de León y combina conservación arquitectónica con exhibición de arte. El conjunto es importante porque muestra cómo la vivienda tradicional leonesa puede adaptarse a un uso cultural contemporáneo sin perder la lectura de sus patios, corredores, proporciones y materiales. Las casas Norberto Ramírez y Derbyshire, entre otras, forman parte del circuito y ayudan a explicar la evolución de la arquitectura doméstica de la ciudad durante los siglos XIX y XX. Además, el centro se convirtió en uno de los espacios artísticos más reconocidos de León, vinculando patrimonio construido y patrimonio artístico. Esta integración entre arquitectura histórica, exposiciones y actividades culturales es una de las razones por las que el centro ocupa un lugar destacado dentro del turismo cultural leonés. Conjunto de casas patrimoniales convertido en importante espacio de arte y cultura.', 12.43471, -86.881941, 30),
  (53, 'centro_cultural_ruben_dario', 'Centro Cultural Rubén Darío', 'Espacio contemporáneo destinado a arte, literatura, biblioteca y tecnología.', 'Centro Cultural Rubén Darío es un punto de interés dentro del patrimonio leonés. Como espacio de memoria, investigación, exhibición o educación, este lugar contribuye a explicar la identidad histórica y cultural de León y de sus comunidades. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Espacio contemporáneo destinado a arte, literatura, biblioteca y tecnología.', 12.436989, -86.881184, 30),
  (54, 'mercadito_de_sutiaba_como_espacio', 'Mercadito de Sutiaba como espacio cultural y tradicional', 'Lugar de intercambio cotidiano y expresión de la identidad comunitaria de Sutiaba.', 'Mercadito de Sutiaba como espacio cultural y tradicional es un punto de interés dentro del patrimonio leonés. Como espacio de memoria, investigación, exhibición o educación, este lugar contribuye a explicar la identidad histórica y cultural de León y de sus comunidades. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Lugar de intercambio cotidiano y expresión de la identidad comunitaria de Sutiaba.', 12.434703, -86.888082, 80),
  (55, 'muralismo_historico_de_leon', 'Muralismo histórico de León', 'Conjunto de murales y representaciones públicas que narran episodios de la historia leonesa.', 'Muralismo histórico de León es un punto de interés dentro del patrimonio leonés. Como espacio de memoria, investigación, exhibición o educación, este lugar contribuye a explicar la identidad histórica y cultural de León y de sus comunidades. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Conjunto de murales y representaciones públicas que narran episodios de la historia leonesa.', 12.435478, -86.87849, 30),
  (56, 'alcaldia_municipal_de_leon_edificio', 'Alcaldía Municipal de León / Edificio Central Marcos Somarriba', 'Edificio institucional integrante del conjunto patrimonial del centro histórico.', 'Alcaldía Municipal de León / Edificio Central Marcos Somarriba es un punto de interés dentro del patrimonio leonés. El inmueble aparece dentro de los inventarios patrimoniales de León y ayuda a leer la evolución de la arquitectura civil, residencial, institucional o de servicios de la ciudad. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Edificio institucional integrante del conjunto patrimonial del centro histórico.', 12.435317, -86.879274, 30),
  (57, 'palacio_municipal_hoy_museo_de_la', 'Palacio Municipal, hoy Museo de la Insurrección', 'Edificio civil reutilizado como espacio de memoria histórica.', 'Palacio Municipal, hoy Museo de la Insurrección es un punto de interés dentro del patrimonio leonés. El inmueble aparece dentro de los inventarios patrimoniales de León y ayuda a leer la evolución de la arquitectura civil, residencial, institucional o de servicios de la ciudad. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Edificio civil reutilizado como espacio de memoria histórica.', 12.434634, -86.879385, 30),
  (61, 'antigua_estacion_del_ferrocarril', 'Antigua Estación del Ferrocarril', 'Infraestructura ferroviaria histórica que recuerda la modernización y movilidad de León.', 'Antigua Estación del Ferrocarril es un punto de interés dentro del patrimonio leonés. El inmueble aparece dentro de los inventarios patrimoniales de León y ayuda a leer la evolución de la arquitectura civil, residencial, institucional o de servicios de la ciudad. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Infraestructura ferroviaria histórica que recuerda la modernización y movilidad de León.', 12.440234, -86.873578, 80),
  (74, 'casa_de_la_familia_lacayo_hotel_la_perla', 'Casa de la Familia Lacayo / Hotel La Perla', 'Edificio de memoria hotelera y residencial integrado al patrimonio urbano.', 'Casa de la Familia Lacayo / Hotel La Perla es un punto de interés dentro del patrimonio leonés. El inmueble aparece dentro de los inventarios patrimoniales de León y ayuda a leer la evolución de la arquitectura civil, residencial, institucional o de servicios de la ciudad. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Edificio de memoria hotelera y residencial integrado al patrimonio urbano.', 12.437503, -86.87937, 30),
  (79, 'conjunto_de_las_cuatro_esquinas', 'Conjunto de las Cuatro Esquinas', 'Conjunto residencial asociado a la memoria familiar de Rubén Darío y a la arquitectura tradicional.', 'Conjunto de las Cuatro Esquinas es un punto de interés dentro del patrimonio leonés. El inmueble aparece dentro de los inventarios patrimoniales de León y ayuda a leer la evolución de la arquitectura civil, residencial, institucional o de servicios de la ciudad. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Conjunto residencial asociado a la memoria familiar de Rubén Darío y a la arquitectura tradicional.', 12.434871, -86.882862, 30),
  (89, 'casa_buzon_de_los_bervis', 'Casa Buzón de los Bervis', 'Casa de memoria revolucionaria situada en el Barrio Indígena de Sutiaba.', 'Casa Buzón de los Bervis es un punto de interés dentro del patrimonio leonés. Este lugar forma parte de la memoria política de León y permite comprender la importancia que tuvo la ciudad en los conflictos sociales y revolucionarios del siglo XX. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Casa de memoria revolucionaria situada en el Barrio Indígena de Sutiaba.', 12.431003, -86.893036, 80),
  (91, 'monumento_donde_cayo_luisa_amanda', 'Monumento donde cayó Luisa Amanda Espinoza y Enrique Lorente', 'Lugar señalizado de memoria sobre hechos de la lucha contra la dictadura.', 'Monumento donde cayó Luisa Amanda Espinoza y Enrique Lorente es un punto de interés dentro del patrimonio leonés. Este lugar forma parte de la memoria política de León y permite comprender la importancia que tuvo la ciudad en los conflictos sociales y revolucionarios del siglo XX. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Lugar señalizado de memoria sobre hechos de la lucha contra la dictadura.', 12.447921, -86.876484, 80),
  (92, 'placa_a_los_heroes_y_martires_de', 'Placa a los Héroes y Mártires de Veracruz', 'Elemento conmemorativo que preserva la memoria de los acontecimientos de Veracruz.', 'Placa a los Héroes y Mártires de Veracruz es un punto de interés dentro del patrimonio leonés. Este lugar forma parte de la memoria política de León y permite comprender la importancia que tuvo la ciudad en los conflictos sociales y revolucionarios del siglo XX. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Elemento conmemorativo que preserva la memoria de los acontecimientos de Veracruz.', 12.42683, -86.91279, 30),
  (93, 'placa_de_la_iglesia_el_calvario', 'Placa de la Iglesia El Calvario vinculada a los hechos de la insurrección', 'Señal de memoria integrada al paisaje histórico del templo y su entorno.', 'Placa de la Iglesia El Calvario vinculada a los hechos de la insurrección es un punto de interés dentro del patrimonio leonés. Este lugar forma parte de la memoria política de León y permite comprender la importancia que tuvo la ciudad en los conflictos sociales y revolucionarios del siglo XX. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Señal de memoria integrada al paisaje histórico del templo y su entorno.', 12.43179, -86.872782, 30),
  (95, 'reparto_veracruz_sitio_historico_de_los', 'Reparto Veracruz / sitio histórico de los Héroes de Veracruz', 'Sector urbano asociado a hechos de memoria revolucionaria y comunitaria.', 'Reparto Veracruz / sitio histórico de los Héroes de Veracruz es un punto de interés dentro del patrimonio leonés. Este lugar forma parte de la memoria política de León y permite comprender la importancia que tuvo la ciudad en los conflictos sociales y revolucionarios del siglo XX. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Sector urbano asociado a hechos de memoria revolucionaria y comunitaria.', 12.42683, -86.91279, 30),
  (25, 'iglesia_san_francisco_de_asis', 'Iglesia San Francisco de Asís', 'Templo y convento histórico relacionado con la tradición franciscana y la ruta de Darío.', 'Iglesia San Francisco de Asís es un punto de interés dentro del patrimonio leonés. En el conjunto religioso de León, este templo o ruina forma parte del paisaje que hizo de la ciudad un referente del patrimonio colonial y de la tradición religiosa nicaragüense. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Templo y convento histórico relacionado con la tradición franciscana y la ruta de Darío.', 12.435262, -86.881586, 30),
  (26, 'iglesia_san_juan_bautista_de_sutiaba', 'Iglesia San Juan Bautista de Sutiaba', 'Principal templo histórico del barrio indígena de Sutiaba.', 'La Iglesia San Juan Bautista de Sutiaba se encuentra frente a la plaza principal del barrio indígena de Sutiaba y forma parte de un conjunto patrimonial que conecta la historia religiosa con la memoria indígena de León. Su arquitectura se reconoce por una fachada de cuerpos decrecientes, elementos clásicos y un interior sobrio con pinturas, adornos dorados y un púlpito de madera. El templo es especialmente importante porque Sutiaba conserva una tradición histórica anterior a la ciudad colonial y porque sus espacios religiosos fueron utilizados para reorganizar la vida comunitaria durante la época colonial. A su alrededor se encuentran la Casa Cural, el Museo de Arte Sacro, el Museo Comunitario Marina Maradiaga y el Museo Arqueológico Adiact, lo que convierte al sector en uno de los núcleos culturales más densos de León. Principal templo histórico del barrio indígena de Sutiaba.', 12.433829, -86.895287, 30),
  (27, 'iglesia_san_juan_de_dios', 'Iglesia San Juan de Dios', 'Templo tradicional declarado Patrimonio Artístico Nacional en 1983.', 'Iglesia San Juan de Dios es un punto de interés dentro del patrimonio leonés. En el conjunto religioso de León, este templo o ruina forma parte del paisaje que hizo de la ciudad un referente del patrimonio colonial y de la tradición religiosa nicaragüense. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Templo tradicional declarado Patrimonio Artístico Nacional en 1983.', 12.43427, -86.881517, 30),
  (28, 'iglesia_san_felipe_apostol', 'Iglesia San Felipe Apóstol', 'Iglesia del barrio San Felipe, importante en las tradiciones de La Gritería.', 'Iglesia San Felipe Apóstol es un punto de interés dentro del patrimonio leonés. En el conjunto religioso de León, este templo o ruina forma parte del paisaje que hizo de la ciudad un referente del patrimonio colonial y de la tradición religiosa nicaragüense. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Iglesia del barrio San Felipe, importante en las tradiciones de La Gritería.', 12.442313, -86.880432, 80),
  (29, 'santuario_nuestra_senora_de_guadalupe', 'Santuario Nuestra Señora de Guadalupe', 'Santuario del barrio Guadalupe, asociado a celebraciones religiosas y tradiciones locales.', 'Santuario Nuestra Señora de Guadalupe es un punto de interés dentro del patrimonio leonés. En el conjunto religioso de León, este templo o ruina forma parte del paisaje que hizo de la ciudad un referente del patrimonio colonial y de la tradición religiosa nicaragüense. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Santuario del barrio Guadalupe, asociado a celebraciones religiosas y tradiciones locales.', 12.427828, -86.878017, 80),
  (30, 'iglesia_san_nicolas_de_tolentino_del', 'Iglesia San Nicolás de Tolentino del Laborío', 'Templo del barrio Laborío con raíces coloniales.', 'Iglesia San Nicolás de Tolentino del Laborío es un punto de interés dentro del patrimonio leonés. En el conjunto religioso de León, este templo o ruina forma parte del paisaje que hizo de la ciudad un referente del patrimonio colonial y de la tradición religiosa nicaragüense. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Templo del barrio Laborío con raíces coloniales.', 12.432261, -86.883314, 80),
  (31, 'iglesia_nuestra_senora_del_pilar_de', 'Iglesia Nuestra Señora del Pilar de Zaragoza', 'Templo ecléctico de piedra con rasgos que recuerdan una fortaleza.', 'Iglesia Nuestra Señora del Pilar de Zaragoza es un punto de interés dentro del patrimonio leonés. En el conjunto religioso de León, este templo o ruina forma parte del paisaje que hizo de la ciudad un referente del patrimonio colonial y de la tradición religiosa nicaragüense. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Templo ecléctico de piedra con rasgos que recuerdan una fortaleza.', 12.437049, -86.8848, 80),
  (35, 'iglesia_san_isidro_labrador', 'Iglesia San Isidro Labrador', 'Templo de tradición parroquial y devocional del municipio.', 'Iglesia San Isidro Labrador es un punto de interés dentro del patrimonio leonés. En el conjunto religioso de León, este templo o ruina forma parte del paisaje que hizo de la ciudad un referente del patrimonio colonial y de la tradición religiosa nicaragüense. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Templo de tradición parroquial y devocional del municipio.', 12.444459, -86.866928, 80),
  (41, 'ruinas_de_ermita_san_sebastian_sutiaba', 'Ruinas de Ermita San Sebastián, Sutiaba', 'Vestigio religioso vinculado al antiguo paisaje ceremonial de Sutiaba.', 'Ruinas de Ermita San Sebastián, Sutiaba es un punto de interés dentro del patrimonio leonés. En el conjunto religioso de León, este templo o ruina forma parte del paisaje que hizo de la ciudad un referente del patrimonio colonial y de la tradición religiosa nicaragüense. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Vestigio religioso vinculado al antiguo paisaje ceremonial de Sutiaba.', 12.435115, -86.902857, 80),
  (50, 'centro_sociocultural_de_sutiaba_marina', 'Centro Sociocultural de Sutiaba Marina Maradiaga', 'Espacio comunitario dedicado a la cultura, memoria y creatividad de Sutiaba.', 'Centro Sociocultural de Sutiaba Marina Maradiaga es un punto de interés dentro del patrimonio leonés. Como espacio de memoria, investigación, exhibición o educación, este lugar contribuye a explicar la identidad histórica y cultural de León y de sus comunidades. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Espacio comunitario dedicado a la cultura, memoria y creatividad de Sutiaba.', 12.433703, -86.896258, 30),
  (51, 'museo_de_arte_sacro_monsenor_cesar', 'Museo de Arte Sacro Monseñor César Bosco Vivas Robelo', 'Colección y espacio de interpretación del patrimonio religioso de Sutiaba.', 'Museo de Arte Sacro Monseñor César Bosco Vivas Robelo es un punto de interés dentro del patrimonio leonés. Como espacio de memoria, investigación, exhibición o educación, este lugar contribuye a explicar la identidad histórica y cultural de León y de sus comunidades. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Colección y espacio de interpretación del patrimonio religioso de Sutiaba.', 12.433619, -86.895496, 30),
  (52, 'biblioteca_publica_ruben_dario', 'Biblioteca Pública Rubén Darío', 'Biblioteca pública que prolonga la tradición literaria de la ciudad y el legado de Darío.', 'Biblioteca Pública Rubén Darío es un punto de interés dentro del patrimonio leonés. Como espacio de memoria, investigación, exhibición o educación, este lugar contribuye a explicar la identidad histórica y cultural de León y de sus comunidades. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Biblioteca pública que prolonga la tradición literaria de la ciudad y el legado de Darío.', 12.436966, -86.881058, 30),
  (58, 'colegio_tridentino_san_ramon', 'Colegio Tridentino San Ramón', 'Edificio educativo de gran antigüedad y relevancia urbana, situado frente al parque central.', 'Colegio Tridentino San Ramón es un punto de interés dentro del patrimonio leonés. El inmueble aparece dentro de los inventarios patrimoniales de León y ayuda a leer la evolución de la arquitectura civil, residencial, institucional o de servicios de la ciudad. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Edificio educativo de gran antigüedad y relevancia urbana, situado frente al parque central.', 12.434331, -86.877941, 30),
  (59, 'palacio_episcopal', 'Palacio Episcopal', 'Sede episcopal histórica del conjunto religioso y urbano alrededor de la Catedral.', 'Palacio Episcopal es un punto de interés dentro del patrimonio leonés. El inmueble aparece dentro de los inventarios patrimoniales de León y ayuda a leer la evolución de la arquitectura civil, residencial, institucional o de servicios de la ciudad. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Sede episcopal histórica del conjunto religioso y urbano alrededor de la Catedral.', 12.4351, -86.8784, 30),
  (60, 'inmueble_de_la_facultad_de_derecho_de', 'Inmueble de la Facultad de Derecho de la UNAN-León', 'Edificio universitario integrado al paisaje patrimonial del centro histórico.', 'Inmueble de la Facultad de Derecho de la UNAN-León es un punto de interés dentro del patrimonio leonés. El inmueble aparece dentro de los inventarios patrimoniales de León y ayuda a leer la evolución de la arquitectura civil, residencial, institucional o de servicios de la ciudad. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Edificio universitario integrado al paisaje patrimonial del centro histórico.', 12.439256, -86.882129, 80),
  (66, 'hospital_escuela_oscar_danilo_rosales', 'Hospital Escuela Oscar Danilo Rosales (HEODRA)', 'Institución sanitaria de enorme peso en la vida universitaria y social de León.', 'Hospital Escuela Oscar Danilo Rosales (HEODRA) es un punto de interés dentro del patrimonio leonés. El inmueble aparece dentro de los inventarios patrimoniales de León y ayuda a leer la evolución de la arquitectura civil, residencial, institucional o de servicios de la ciudad. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Institución sanitaria de enorme peso en la vida universitaria y social de León.', 12.453109, -86.869116, 80),
  (67, 'puente_de_guadalupe', 'Puente de Guadalupe', 'Obra urbana histórica relacionada con el acceso y la estructura vial tradicional de la ciudad.', 'Puente de Guadalupe es un punto de interés dentro del patrimonio leonés. El inmueble aparece dentro de los inventarios patrimoniales de León y ayuda a leer la evolución de la arquitectura civil, residencial, institucional o de servicios de la ciudad. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Obra urbana histórica relacionada con el acceso y la estructura vial tradicional de la ciudad.', 12.43044, -86.878193, 80),
  (82, 'fortin_de_acosasco', 'Fortín de Acosasco', 'Fortificación militar de 1890 y sitio clave de la memoria política de León.', 'El Fortín de Acosasco es una fortificación militar construida en 1890 en una posición estratégica sobre un cerro desde el que se domina buena parte de León y su entorno. Con el tiempo tuvo usos vinculados a la seguridad militar y a la historia política nacional; durante el periodo de la dictadura somocista funcionó también como base y lugar de reclusión. La toma del fortín por fuerzas sandinistas el 7 de julio de 1979 hizo que el sitio quedara incorporado a la memoria de la revolución y de la liberación de León. Su estructura, con muros gruesos y un trazado defensivo, conserva la lectura material de una arquitectura militar adaptada al paisaje. Hoy es, sobre todo, un sitio de memoria y un mirador histórico que ayuda a entender la posición estratégica de León. Fortificación militar de 1890 y sitio clave de la memoria política de León.', 12.417292, -86.892784, 80),
  (87, 'mausoleo_a_los_heroes_y_martires_de_la', 'Mausoleo a los Héroes y Mártires de la Revolución', 'Espacio funerario y conmemorativo de enorme carga simbólica en la ciudad.', 'Mausoleo a los Héroes y Mártires de la Revolución es un punto de interés dentro del patrimonio leonés. Este lugar forma parte de la memoria política de León y permite comprender la importancia que tuvo la ciudad en los conflictos sociales y revolucionarios del siglo XX. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Espacio funerario y conmemorativo de enorme carga simbólica en la ciudad.', 12.435561, -86.878447, 30),
  (90, 'galeria_heroes_y_martires_de_leon', 'Galería Héroes y Mártires de León', 'Espacio de memoria comunitaria dedicado a personas vinculadas a la historia revolucionaria.', 'Galería Héroes y Mártires de León es un punto de interés dentro del patrimonio leonés. Este lugar forma parte de la memoria política de León y permite comprender la importancia que tuvo la ciudad en los conflictos sociales y revolucionarios del siglo XX. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Espacio de memoria comunitaria dedicado a personas vinculadas a la historia revolucionaria.', 12.436343, -86.879875, 30),
  (94, 'cancha_espacio_historico_23_de_julio', 'Cancha / espacio histórico 23 de Julio', 'Espacio urbano relacionado con la memoria juvenil y política de León.', 'Cancha / espacio histórico 23 de Julio es un punto de interés dentro del patrimonio leonés. Este lugar forma parte de la memoria política de León y permite comprender la importancia que tuvo la ciudad en los conflictos sociales y revolucionarios del siglo XX. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Espacio urbano relacionado con la memoria juvenil y política de León.', 12.435712, -86.879306, 30),
  (96, 'cementerio_de_guadalupe', 'Cementerio de Guadalupe', 'Cementerio histórico de León, relevante por su patrimonio funerario y memoria local.', 'Cementerio de Guadalupe es un punto de interés dentro del patrimonio leonés. Este espacio urbano forma parte de la estructura histórica de León y ayuda a interpretar la relación entre plazas, monumentos, convivencia ciudadana y memoria colectiva. Los inventarios y guías consultados lo relacionan con el tejido histórico de la ciudad, ya sea por su arquitectura, por los acontecimientos que se desarrollaron en el lugar o por su función cultural. Su valor se entiende mejor al observarlo dentro del conjunto urbano: calles, plazas, templos, viviendas, instituciones y espacios de memoria forman una red que conserva distintas capas de la historia de León, desde la época colonial y republicana hasta la vida intelectual, universitaria y política del siglo XX. Más que un edificio aislado, este sitio funciona como evidencia de cómo la sociedad leonesa construyó su identidad y cómo esa identidad sigue presente en el patrimonio material y en las prácticas culturales actuales. Cementerio histórico de León, relevante por su patrimonio funerario y memoria local.', 12.423501, -86.877141, 80)
) as v(id, clave, nombre, descripcion_corta, historia, latitud, longitud, radio_sello_metros)
join public.insignia i on i.clave = v.clave;

-- 3. Puerto Salvador Allende (Managua) -- fuera de la lista original,
--    con insignia propia 'puerto_salvador_allende' (ya no reutiliza
--    'territory' como placeholder).
insert into public.sitio (id, insignia_id, nombre, descripcion_corta, historia, latitud, longitud, radio_sello_metros)
values (
  98,
  (select id from public.insignia where clave = 'puerto_salvador_allende'),
  'Puerto Salvador Allende',
  'Malecón turístico sobre el Lago Xolotlán, en Managua, con restaurantes, paseos en bote y vista al volcán Momotombo.',
  'El Puerto Salvador Allende está en la orilla sur del Lago Xolotlán (Lago de Managua), en el antiguo centro de la capital, cerca del Teatro Nacional Rubén Darío y la vieja Catedral de Managua. Lleva el nombre del expresidente chileno Salvador Allende y se desarrolló como un malecón moderno con restaurantes, kioscos y paseos en bote hacia la Isla del Amor, desde donde se aprecia el volcán Momotombo al otro lado del lago.',
  12.164023,
  -86.278134,
  80
);

-- 4. Corrección de radio en 3 sitios YA EXISTENTES (no se tocan sus demás
--    columnas): ahora tienen un vecino nuevo a menos de 150m.
--    id1 (Catedral de León) a 30m del Palacio Episcopal (id59); id5
--    (Iglesia San Juan Bautista) a 87.9m de id74 (Casa de la Familia
--    Lacayo/Hotel La Perla); id7 (Teatro Municipal) a 120.4m de id27
--    (Iglesia San Juan de Dios).
update public.sitio set radio_sello_metros = 30 where id in (1, 5, 7);

-- 5. Reajustar las secuencias identity para que el próximo insert
--    automático no choque con los ids explícitos insertados arriba.
select setval(pg_get_serial_sequence('sitio','id'), (select max(id) from public.sitio));
select setval(pg_get_serial_sequence('insignia','id'), (select max(id) from public.insignia));

commit;
