-- docs/migrations/019_resenas.sql
--
-- Reseñas de negocios.
--
--   - Un turista puede reseñar un negocio solo si tiene al menos un sello QR de ese
--     negocio (sello.qr_sello_id -> qr_sello.negocio_id). Se valida en la política
--     de INSERT, no solo ocultando el botón en el frontend.
--   - Una reseña por usuario y negocio (UNIQUE). Para cambiarla, se edita (UPDATE).
--   - El dueño del negocio puede responder (respuesta_emprendedor).
--   - Lectura pública con el mismo criterio que fotos/horarios/productos/QR
--     (negocio_visible): la reseña se oculta si el negocio está vencido (016).
--   - Nadie borra salvo admin_borrar_resena (solo rol admin).
--
-- Por qué hay un trigger además de permisos por columna:
--   Los GRANT por columna son por ROL, no por política. El turista y el dueño son el
--   mismo rol (authenticated) y las dos políticas de UPDATE se suman (OR). Con solo
--   GRANT, el turista podría escribir respuesta_emprendedor en su propia reseña y el
--   dueño podría cambiar la calificación de otro. Entonces:
--     - GRANT UPDATE solo sobre calificacion, comentario, respuesta_emprendedor
--       (nadie toca negocio_id, usuario_id, fecha ni id);
--     - resena_validar_update() exige que calificacion/comentario solo los cambie el
--       autor y respuesta_emprendedor solo el dueño;
--     - fecha_respuesta la pone el trigger (now()), no el cliente: no se puede falsear.
--
-- Supabase da por defecto ALL a anon y authenticated en tablas nuevas de public
-- (pg_default_acl): aquí se revoca todo y se otorga solo lo necesario.

begin;

-- -----------------------------------------------------------------------------
-- 1. Tabla
-- -----------------------------------------------------------------------------
create table public.resena (
    id                      bigint      generated by default as identity primary key,
    negocio_id              integer     not null references public.negocio (id) on delete cascade,
    usuario_id              uuid        not null default auth.uid()
                                        references public.usuario (id) on delete cascade,
    calificacion            smallint    not null check (calificacion between 1 and 5),
    comentario              text        check (comentario is null or char_length(comentario) <= 2000),
    fecha                   timestamptz not null default now(),
    respuesta_emprendedor   text        check (respuesta_emprendedor is null or char_length(respuesta_emprendedor) <= 2000),
    fecha_respuesta         timestamptz,
    constraint resena_una_por_usuario_y_negocio unique (negocio_id, usuario_id)
);

comment on table public.resena is
    'Reseñas de negocios. Solo con sello QR del negocio; una por usuario y negocio; el dueño puede responder (019).';

alter table public.resena enable row level security;

-- -----------------------------------------------------------------------------
-- 2. Permisos de tabla / columna
-- -----------------------------------------------------------------------------
revoke all on public.resena from anon, authenticated;

grant select on public.resena to anon, authenticated;
grant insert (negocio_id, usuario_id, calificacion, comentario) on public.resena to authenticated;
grant update (calificacion, comentario, respuesta_emprendedor) on public.resena to authenticated;
-- Sin DELETE para anon/authenticated: solo admin_borrar_resena.

-- -----------------------------------------------------------------------------
-- 3. Políticas
-- -----------------------------------------------------------------------------
-- Lectura: mismo criterio que las tablas hijas del negocio.
create policy resena_select_visible on public.resena
    for select to anon, authenticated
    using (public.negocio_visible(negocio_id));

-- Alta: a nombre propio, no del propio negocio, y solo con sello QR de ese negocio.
create policy resena_insert_con_sello on public.resena
    for insert to authenticated
    with check (
        usuario_id = auth.uid()
        and not public.es_duenio_negocio(negocio_id)
        and exists (
            select 1
            from public.sello s
            join public.qr_sello q on q.id = s.qr_sello_id
            where s.usuario_id = auth.uid()
              and q.negocio_id = resena.negocio_id
        )
    );

-- Edición por el autor (calificación y comentario; el trigger limita columnas).
create policy resena_update_autor on public.resena
    for update to authenticated
    using (usuario_id = auth.uid())
    with check (usuario_id = auth.uid());

-- Respuesta del dueño del negocio (el trigger limita columnas).
create policy resena_update_duenio on public.resena
    for update to authenticated
    using (public.es_duenio_negocio(negocio_id))
    with check (public.es_duenio_negocio(negocio_id));

-- -----------------------------------------------------------------------------
-- 4. Trigger: quién puede cambiar qué columna
-- -----------------------------------------------------------------------------
create or replace function public.resena_validar_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  -- Solo aplica a usuarios de la app; service_role / postgres / funciones de admin pasan.
  if current_user <> 'authenticated' then
    return new;
  end if;

  if (new.calificacion is distinct from old.calificacion
      or new.comentario is distinct from old.comentario)
     and old.usuario_id is distinct from auth.uid() then
    raise exception 'Solo el autor puede cambiar la calificación o el comentario de una reseña.'
      using errcode = '42501';
  end if;

  if new.respuesta_emprendedor is distinct from old.respuesta_emprendedor
     and not public.es_duenio_negocio(old.negocio_id) then
    raise exception 'Solo el dueño del negocio puede responder una reseña.'
      using errcode = '42501';
  end if;

  -- fecha_respuesta la decide el servidor.
  if new.respuesta_emprendedor is distinct from old.respuesta_emprendedor then
    new.fecha_respuesta := case when new.respuesta_emprendedor is null then null else now() end;
  else
    new.fecha_respuesta := old.fecha_respuesta;
  end if;

  return new;
end;
$$;

create trigger resena_validar_update
    before update on public.resena
    for each row execute function public.resena_validar_update();

-- -----------------------------------------------------------------------------
-- 5. Borrado por admin
-- -----------------------------------------------------------------------------
create or replace function public.admin_borrar_resena(p_resena_id bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
DECLARE
  v_rol text;
BEGIN
  SELECT rol INTO v_rol FROM usuario WHERE id = auth.uid();
  IF v_rol IS DISTINCT FROM 'admin' THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'No tienes permiso de administrador.');
  END IF;

  DELETE FROM resena WHERE id = p_resena_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Reseña no encontrada.');
  END IF;

  RETURN jsonb_build_object('exito', true, 'mensaje', 'Reseña eliminada.');
END;
$function$;

comment on function public.admin_borrar_resena(bigint) is
    'Borra una reseña (moderación manual). Solo rol=admin (019).';

revoke execute on function public.admin_borrar_resena(bigint) from public, anon;
grant execute on function public.admin_borrar_resena(bigint) to authenticated, service_role;

commit;
