-- docs/migrations/021_actividad_negocio_y_solicitud_sello.sql
--
-- Actividades de negocio con solicitud de sello aprobada por admin, y arreglo de la
-- creación de eventos (que nunca funcionó).
--
-- 1. actividad_negocio: actividades del negocio. Con fecha_inicio y fecha_fin son
--    públicas (como un evento); sin fechas, solo las ve el dueño (y el admin).
--    Opcionalmente piden sello (solicita_sello) -> estado_sello pendiente; el admin
--    aprueba (se crea el qr_sello real) o rechaza.
-- 2. estado_sello, qr_sello_id, motivo_rechazo_sello y evento_id NO los escribe el
--    dueño (ni por GRANT ni por trigger): solo las funciones de admin / evento.
--    El trigger actividad_negocio_estado_sello calcula estado_sello a partir de
--    solicita_sello (insert, solicitar, retirar la solicitud, re-solicitar tras rechazo).
-- 3. admin_aprobar_sello: crea el qr_sello directamente (mismo token que
--    crear_actividad_qr). No puede llamar a crear_actividad_qr: esa función valida
--    es_duenio_negocio con el auth.uid() del que llama, que aquí es el admin.
-- 4. admin_rechazar_sello: solo sobre solicitudes 'pendiente'.
-- 5. Eventos: el insert desde el cliente (useNegocio.crearActividadQR) fallaba siempre
--    por RLS (evento no tiene política de INSERT) y el error se silenciaba. Se
--    reemplaza por crear_evento_desde_actividad (SECURITY DEFINER): dueño, negocio
--    activo y vigente, actividad con fechas. Idempotente vía actividad_negocio.evento_id.
--    NO se agrega política de INSERT en evento (la función no la necesita) y se revoca
--    la escritura directa de anon/authenticated sobre evento.
--
-- OJO (pendiente, no se cambia aquí para no romper la app actual): crear_actividad_qr
-- sigue disponible para el dueño y crea QR escaneables al instante, sin aprobación.
-- Cuando el frontend pase a solicitar sellos, hay que revocarle EXECUTE a
-- authenticated; si no, la aprobación del admin se puede saltar llamando a la API.

begin;

-- -----------------------------------------------------------------------------
-- 1. Tabla
-- -----------------------------------------------------------------------------
create table public.actividad_negocio (
    id                      bigint      generated by default as identity primary key,
    negocio_id              integer     not null references public.negocio (id) on delete cascade,
    nombre                  text        not null check (char_length(btrim(nombre)) between 1 and 120),
    descripcion             text        check (descripcion is null or char_length(descripcion) <= 2000),
    fecha_inicio            date,
    fecha_fin               date,
    solicita_sello          boolean     not null default false,
    estado_sello            text        not null default 'no_solicitado'
                                        check (estado_sello in ('no_solicitado', 'pendiente', 'aprobado', 'rechazado')),
    justificacion_sello     text        check (justificacion_sello is null or char_length(justificacion_sello) <= 2000),
    motivo_rechazo_sello    text,
    qr_sello_id             integer     references public.qr_sello (id) on delete set null,
    evento_id               integer     references public.evento (id) on delete set null,
    fecha_creacion          timestamptz not null default now(),
    constraint actividad_fechas_ambas_o_ninguna check ((fecha_inicio is null) = (fecha_fin is null)),
    constraint actividad_fechas_en_orden check (fecha_fin is null or fecha_fin >= fecha_inicio),
    constraint actividad_qr_solo_si_aprobado check (qr_sello_id is null or estado_sello = 'aprobado')
);

create index idx_actividad_negocio_negocio on public.actividad_negocio (negocio_id);
create index idx_actividad_negocio_pendientes on public.actividad_negocio (estado_sello) where estado_sello = 'pendiente';

comment on table public.actividad_negocio is
    'Actividades de un negocio. Con fechas son públicas (como evento). Pueden pedir sello: el admin aprueba (crea qr_sello) o rechaza (021).';

alter table public.actividad_negocio enable row level security;

-- -----------------------------------------------------------------------------
-- 2. Permisos (Supabase da ALL por defecto a anon/authenticated en tablas nuevas)
-- -----------------------------------------------------------------------------
revoke all on public.actividad_negocio from anon, authenticated;

grant select on public.actividad_negocio to anon, authenticated;
grant insert (negocio_id, nombre, descripcion, fecha_inicio, fecha_fin, solicita_sello, justificacion_sello)
    on public.actividad_negocio to authenticated;
grant update (nombre, descripcion, fecha_inicio, fecha_fin, solicita_sello, justificacion_sello)
    on public.actividad_negocio to authenticated;
-- Sin DELETE para anon/authenticated.

-- -----------------------------------------------------------------------------
-- 3. Políticas
-- -----------------------------------------------------------------------------
-- Pública: negocio visible (activo y vigente, 016) y actividad con fechas.
create policy actividad_negocio_select_publica on public.actividad_negocio
    for select to anon, authenticated
    using (public.negocio_visible(negocio_id) and fecha_inicio is not null and fecha_fin is not null);

-- El dueño ve todas las suyas, con o sin fechas.
create policy actividad_negocio_select_duenio on public.actividad_negocio
    for select to authenticated
    using (public.es_duenio_negocio(negocio_id));

-- El admin ve todas (para revisar solicitudes de sello).
create policy actividad_negocio_select_admin on public.actividad_negocio
    for select to authenticated
    using (exists (select 1 from public.usuario u where u.id = auth.uid() and u.rol = 'admin'));

create policy actividad_negocio_insert_duenio on public.actividad_negocio
    for insert to authenticated
    with check (public.es_duenio_negocio(negocio_id));

create policy actividad_negocio_update_duenio on public.actividad_negocio
    for update to authenticated
    using (public.es_duenio_negocio(negocio_id))
    with check (public.es_duenio_negocio(negocio_id));

-- -----------------------------------------------------------------------------
-- 4. Trigger: estado_sello lo decide la base, no el cliente
-- -----------------------------------------------------------------------------
create or replace function public.actividad_negocio_estado_sello()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  -- Las funciones de admin / evento (SECURITY DEFINER) corren como postgres y pasan.
  if current_user <> 'authenticated' then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.estado_sello := case when new.solicita_sello then 'pendiente' else 'no_solicitado' end;
    new.qr_sello_id := null;
    new.motivo_rechazo_sello := null;
    new.evento_id := null;
    return new;
  end if;

  -- UPDATE: columnas de admin/evento siempre se conservan.
  new.estado_sello := old.estado_sello;
  new.qr_sello_id := old.qr_sello_id;
  new.motivo_rechazo_sello := old.motivo_rechazo_sello;
  new.evento_id := old.evento_id;

  if old.estado_sello = 'aprobado' then
    if new.solicita_sello is distinct from old.solicita_sello then
      raise exception 'Esta actividad ya tiene un sello aprobado.' using errcode = '42501';
    end if;
  elsif new.solicita_sello and not old.solicita_sello then
    -- Pide sello por primera vez (o de nuevo tras retirarlo).
    new.estado_sello := 'pendiente';
    new.motivo_rechazo_sello := null;
  elsif not new.solicita_sello and old.solicita_sello then
    -- Retira la solicitud (pendiente o rechazada).
    new.estado_sello := 'no_solicitado';
    new.motivo_rechazo_sello := null;
  elsif new.solicita_sello and old.estado_sello = 'rechazado'
        and new.justificacion_sello is distinct from old.justificacion_sello then
    -- Re-solicita tras un rechazo, con una justificación nueva.
    new.estado_sello := 'pendiente';
    new.motivo_rechazo_sello := null;
  end if;

  return new;
end;
$$;

create trigger actividad_negocio_estado_sello
    before insert or update on public.actividad_negocio
    for each row execute function public.actividad_negocio_estado_sello();

-- -----------------------------------------------------------------------------
-- 5. Admin: aprobar / rechazar sello
-- -----------------------------------------------------------------------------
create or replace function public.admin_aprobar_sello(p_actividad_id bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
DECLARE
  v_rol text;
  v_act actividad_negocio;
  v_qr_id integer;
BEGIN
  SELECT rol INTO v_rol FROM usuario WHERE id = auth.uid();
  IF v_rol IS DISTINCT FROM 'admin' THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'No tienes permiso de administrador.');
  END IF;

  SELECT * INTO v_act FROM actividad_negocio WHERE id = p_actividad_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Actividad no encontrada.');
  END IF;
  IF NOT v_act.solicita_sello OR v_act.estado_sello <> 'pendiente' THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Esta actividad no tiene una solicitud de sello pendiente.');
  END IF;

  -- Mismo token que crear_actividad_qr (008). Vence con la actividad, si tiene fechas.
  INSERT INTO qr_sello (negocio_id, token, nombre_actividad, fecha_expiracion)
  VALUES (v_act.negocio_id,
          upper(replace(gen_random_uuid()::text, '-', '')),
          v_act.nombre,
          v_act.fecha_fin::timestamptz)
  RETURNING id INTO v_qr_id;

  UPDATE actividad_negocio
  SET estado_sello = 'aprobado', qr_sello_id = v_qr_id, motivo_rechazo_sello = NULL
  WHERE id = p_actividad_id;

  RETURN jsonb_build_object('exito', true, 'mensaje', 'Sello aprobado.', 'qr_sello_id', v_qr_id);
END;
$function$;

comment on function public.admin_aprobar_sello(bigint) is
    'Aprueba la solicitud de sello de una actividad pendiente: crea el qr_sello y lo vincula. Solo rol=admin (021).';

create or replace function public.admin_rechazar_sello(p_actividad_id bigint, p_motivo text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
DECLARE
  v_rol text;
BEGIN
  SELECT rol INTO v_rol FROM usuario WHERE id = auth.uid();
  IF v_rol IS DISTINCT FROM 'admin' THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'No tienes permiso de administrador.');
  END IF;

  UPDATE actividad_negocio
  SET estado_sello = 'rechazado', motivo_rechazo_sello = COALESCE(NULLIF(btrim(p_motivo), ''), 'No especificado')
  WHERE id = p_actividad_id
    AND estado_sello = 'pendiente';

  IF NOT FOUND THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Esta actividad no tiene una solicitud de sello pendiente.');
  END IF;

  RETURN jsonb_build_object('exito', true, 'mensaje', 'Sello rechazado.');
END;
$function$;

comment on function public.admin_rechazar_sello(bigint, text) is
    'Rechaza la solicitud de sello de una actividad pendiente, con motivo. Solo rol=admin (021).';

-- -----------------------------------------------------------------------------
-- 6. Evento desde una actividad (reemplaza el insert directo que fallaba)
-- -----------------------------------------------------------------------------
create or replace function public.crear_evento_desde_actividad(p_actividad_id bigint)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
DECLARE
  v_act actividad_negocio;
  v_negocio negocio;
  v_evento_id integer;
BEGIN
  SELECT * INTO v_act FROM actividad_negocio WHERE id = p_actividad_id FOR UPDATE;
  IF NOT FOUND OR NOT public.es_duenio_negocio(v_act.negocio_id) THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'No tienes permiso sobre esta actividad.');
  END IF;

  IF v_act.fecha_inicio IS NULL OR v_act.fecha_fin IS NULL THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'La actividad necesita fecha de inicio y de fin para publicarse como evento.');
  END IF;

  SELECT * INTO v_negocio FROM negocio WHERE id = v_act.negocio_id;
  IF v_negocio.estado <> 'activo'
     OR v_negocio.fecha_vencimiento_suscripcion IS NULL
     OR v_negocio.fecha_vencimiento_suscripcion <= now() THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Tu negocio necesita una suscripción activa para publicar eventos.');
  END IF;

  -- Idempotente: si ya tiene evento, lo devuelve.
  IF v_act.evento_id IS NOT NULL THEN
    RETURN jsonb_build_object('exito', true, 'mensaje', 'La actividad ya tenía su evento.', 'evento_id', v_act.evento_id);
  END IF;

  INSERT INTO evento (negocio_organizador_id, nombre, fecha_inicio, fecha_fin, ubicacion, descripcion)
  VALUES (v_act.negocio_id, v_act.nombre, v_act.fecha_inicio, v_act.fecha_fin,
          v_negocio.nombre_negocio, v_act.descripcion)
  RETURNING id INTO v_evento_id;

  UPDATE actividad_negocio SET evento_id = v_evento_id WHERE id = p_actividad_id;

  RETURN jsonb_build_object('exito', true, 'mensaje', 'Evento publicado.', 'evento_id', v_evento_id);
END;
$function$;

comment on function public.crear_evento_desde_actividad(bigint) is
    'Publica como evento una actividad con fechas. Solo el dueño, con negocio activo y vigente. Idempotente (021).';

-- Permisos de las funciones nuevas
revoke execute on function public.admin_aprobar_sello(bigint) from public, anon;
revoke execute on function public.admin_rechazar_sello(bigint, text) from public, anon;
revoke execute on function public.crear_evento_desde_actividad(bigint) from public, anon;
grant execute on function public.admin_aprobar_sello(bigint) to authenticated, service_role;
grant execute on function public.admin_rechazar_sello(bigint, text) to authenticated, service_role;
grant execute on function public.crear_evento_desde_actividad(bigint) to authenticated, service_role;

-- -----------------------------------------------------------------------------
-- 7. evento: sin escritura directa desde la app (solo vía crear_evento_desde_actividad)
-- -----------------------------------------------------------------------------
revoke insert, update, delete, truncate on public.evento from anon, authenticated;

commit;
