-- docs/migrations/027_cupones.sql
--
-- Cupones: el turista OBTIENE un cupón escaneando el QR del cupón y lo USA mostrando su
-- cupón al negocio y escaneando el QR de CANJE del negocio (uno por negocio, sirve para
-- cualquiera de sus cupones).
--
-- Protección igual a qr_sello desde 008: el token del cupón y el token de canje NO se leen
-- directo (ni authenticated ni anon, tampoco el dueño ni el admin). Toda interacción pasa
-- por funciones SECURITY DEFINER.
--
-- DESVÍO del pedido: el token de canje NO es una columna de negocio.
--   negocio tiene SELECT de tabla completa para anon y authenticated, y useNegocio.js lee con
--   select('*') y .update(...).select(). Una columna nueva se leería sin permiso especial
--   (token expuesto con la clave pública), y protegerla con permisos por columna (como se hizo
--   con qr_sello.token) haría fallar esos select('*') en producción ("permission denied").
--   El token vive en negocio_token_canje (una fila por negocio, sin permisos para anon ni
--   authenticated). Mismo efecto, sin tocar negocio ni el frontend.
--
-- Cuándo se genera el token de canje: la primera vez que el negocio crea un cupón (trigger
--   AFTER INSERT en cupon). No se engancha a admin_aprobar_negocio: no hace falta tocar esa
--   función, cubre a los negocios que ya están activos sin rellenar datos y no deja tokens
--   sin usar en negocios que no ofrecen cupones.
--
-- Fuera de las 8 piezas pedidas, se agrega mis_cupones_negocio(): el dueño no puede leer los
-- tokens directo (por diseño), así que necesita una función para obtener el token de cada
-- cupón y el de canje y poder imprimir los QR (igual que mis_actividades_qr en 008).

begin;

-- -----------------------------------------------------------------------------
-- 1. cupon
-- -----------------------------------------------------------------------------
create table public.cupon (
    id                      bigint      generated by default as identity primary key,
    negocio_id              integer     not null references public.negocio (id) on delete cascade,
    token                   text        not null unique
                                        default upper(replace(gen_random_uuid()::text, '-', '')),
    descripcion             text        not null
                                        check (char_length(btrim(descripcion)) between 1 and 300),
    descuento_porcentaje    integer     not null check (descuento_porcentaje between 1 and 100),
    fecha_expiracion        timestamptz,
    limite_total            integer     check (limite_total is null or limite_total between 1 and 200),
    activo                  boolean     not null default true,
    fecha_creacion          timestamptz not null default now()
);

create index idx_cupon_negocio on public.cupon (negocio_id);

comment on table public.cupon is
    'Cupones de un negocio. Token y lectura solo por funciones SECURITY DEFINER (027).';
comment on column public.cupon.token is
    'Token del QR de "obtener". Generado en la base; no legible por anon/authenticated (027).';
comment on column public.cupon.fecha_expiracion is
    'NULL = sin vencimiento. Vence cuando fecha_expiracion < now(): para que cuente el día completo, guardar el fin del día.';
comment on column public.cupon.limite_total is
    'Cantidad máxima de cupones que se pueden obtener (1 a 200). NULL = sin límite.';
comment on column public.cupon.activo is
    'false = no se puede obtener más. Quien ya lo tiene puede seguir usándolo hasta que venza.';

alter table public.cupon enable row level security;

-- Supabase da ALL por defecto a anon/authenticated en tablas nuevas.
revoke all on public.cupon from anon, authenticated;

-- Sin la columna token (igual que qr_sello en 008).
grant select (id, negocio_id, descripcion, descuento_porcentaje, fecha_expiracion,
              limite_total, activo, fecha_creacion)
    on public.cupon to authenticated;
grant insert (negocio_id, descripcion, descuento_porcentaje, fecha_expiracion, limite_total, activo)
    on public.cupon to authenticated;
grant update (descripcion, descuento_porcentaje, fecha_expiracion, limite_total, activo)
    on public.cupon to authenticated;
-- Sin DELETE: el negocio desactiva, no borra.

create policy cupon_select_duenio on public.cupon
    for select to authenticated
    using (public.es_duenio_negocio(negocio_id));

create policy cupon_select_admin on public.cupon
    for select to authenticated
    using (exists (select 1 from public.usuario u where u.id = auth.uid() and u.rol = 'admin'));

create policy cupon_insert_duenio on public.cupon
    for insert to authenticated
    with check (public.es_duenio_negocio(negocio_id));

create policy cupon_update_duenio on public.cupon
    for update to authenticated
    using (public.es_duenio_negocio(negocio_id))
    with check (public.es_duenio_negocio(negocio_id));

-- -----------------------------------------------------------------------------
-- 2. cupon_obtenido
-- -----------------------------------------------------------------------------
create table public.cupon_obtenido (
    id              bigint      generated by default as identity primary key,
    cupon_id        bigint      not null references public.cupon (id) on delete restrict,
    usuario_id      uuid        not null references public.usuario (id) on delete cascade,
    estado          text        not null default 'obtenido' check (estado in ('obtenido', 'usado')),
    fecha_obtenido  timestamptz not null default now(),
    fecha_uso       timestamptz,
    constraint cupon_obtenido_unico unique (cupon_id, usuario_id),
    constraint cupon_obtenido_uso_coherente check ((estado = 'usado') = (fecha_uso is not null))
);

create index idx_cupon_obtenido_usuario on public.cupon_obtenido (usuario_id);

comment on table public.cupon_obtenido is
    'Qué turista tiene qué cupón y si ya lo usó. Solo lo escriben las funciones SECURITY DEFINER (027).';

alter table public.cupon_obtenido enable row level security;

revoke all on public.cupon_obtenido from anon, authenticated;
grant select on public.cupon_obtenido to authenticated;   -- sin INSERT/UPDATE/DELETE

create policy cupon_obtenido_select_propio on public.cupon_obtenido
    for select to authenticated
    using (usuario_id = auth.uid());

-- -----------------------------------------------------------------------------
-- 3. Token de canje: una fila por negocio, sin ningún permiso para anon/authenticated
-- -----------------------------------------------------------------------------
create table public.negocio_token_canje (
    negocio_id      integer     primary key references public.negocio (id) on delete cascade,
    token           text        not null unique
                                default upper(replace(gen_random_uuid()::text, '-', '')),
    fecha_creacion  timestamptz not null default now()
);

comment on table public.negocio_token_canje is
    'Token del QR de canje de cupones del negocio (uno por negocio). Sin permisos para anon/authenticated: solo funciones SECURITY DEFINER (027).';

alter table public.negocio_token_canje enable row level security;
revoke all on public.negocio_token_canje from anon, authenticated;

-- Se crea la primera vez que el negocio crea un cupón.
create function public.cupon_asegurar_token_canje()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.negocio_token_canje (negocio_id)
  values (new.negocio_id)
  on conflict (negocio_id) do nothing;
  return new;
end;
$$;

revoke execute on function public.cupon_asegurar_token_canje() from public, anon, authenticated;

create trigger cupon_asegurar_token_canje
    after insert on public.cupon
    for each row execute function public.cupon_asegurar_token_canje();

-- -----------------------------------------------------------------------------
-- 4. obtener_cupon(p_token)
-- -----------------------------------------------------------------------------
create or replace function public.obtener_cupon(p_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
DECLARE
  v_uid uuid := auth.uid();
  v_c cupon;
  v_nombre_negocio text;
  v_total integer;
  v_id bigint;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Necesitas iniciar sesión.');
  END IF;

  -- FOR UPDATE: serializa las obtenciones del mismo cupón (el límite no se pasa en paralelo).
  SELECT * INTO v_c FROM cupon WHERE token = p_token FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Código de cupón no válido.');
  END IF;

  IF NOT v_c.activo THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Este cupón ya no está disponible.');
  END IF;

  IF v_c.fecha_expiracion IS NOT NULL AND v_c.fecha_expiracion < now() THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Este cupón ya venció.');
  END IF;

  -- Mismo criterio que canjear_qr_sello (017): el negocio debe seguir participando.
  SELECT nombre_negocio INTO v_nombre_negocio
  FROM negocio
  WHERE id = v_c.negocio_id
    AND estado = 'activo'
    AND fecha_vencimiento_suscripcion > now();
  IF NOT FOUND THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Este negocio ya no está participando en la ruta.');
  END IF;

  -- Antes del límite: quien ya lo tiene ve "Ya tienes este cupón" aunque se haya agotado.
  IF EXISTS (SELECT 1 FROM cupon_obtenido WHERE cupon_id = v_c.id AND usuario_id = v_uid) THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Ya tienes este cupón.');
  END IF;

  IF v_c.limite_total IS NOT NULL THEN
    SELECT count(*) INTO v_total FROM cupon_obtenido WHERE cupon_id = v_c.id;
    IF v_total >= v_c.limite_total THEN
      RETURN jsonb_build_object('exito', false, 'mensaje', 'Este cupón ya alcanzó su límite.');
    END IF;
  END IF;

  INSERT INTO cupon_obtenido (cupon_id, usuario_id)
  VALUES (v_c.id, v_uid)
  RETURNING id INTO v_id;

  RETURN jsonb_build_object(
    'exito', true,
    'mensaje', '¡Cupón obtenido!',
    'cupon_obtenido_id', v_id,
    'cupon', jsonb_build_object(
      'descripcion', v_c.descripcion,
      'descuento_porcentaje', v_c.descuento_porcentaje,
      'fecha_expiracion', v_c.fecha_expiracion,
      'negocio_id', v_c.negocio_id,
      'nombre_negocio', v_nombre_negocio
    )
  );
EXCEPTION
  WHEN unique_violation THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Ya tienes este cupón.');
END;
$function$;

comment on function public.obtener_cupon(text) is
    'El turista obtiene un cupón con el token de su QR. Valida activo, vencimiento, negocio vigente, duplicado y límite (027).';

-- -----------------------------------------------------------------------------
-- 5. mis_cupones_obtenidos()
-- -----------------------------------------------------------------------------
create or replace function public.mis_cupones_obtenidos()
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
DECLARE
  v_uid uuid := auth.uid();
  v_cupones jsonb;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Necesitas iniciar sesión.', 'cupones', '[]'::jsonb);
  END IF;

  -- "disponible" = se puede usar hoy (igual que usar_cupon): sin usar, sin vencer, negocio vigente.
  SELECT coalesce(jsonb_agg(
           jsonb_build_object(
             'id', co.id,
             'estado', co.estado,
             'fecha_obtenido', co.fecha_obtenido,
             'fecha_uso', co.fecha_uso,
             'descripcion', c.descripcion,
             'descuento_porcentaje', c.descuento_porcentaje,
             'fecha_expiracion', c.fecha_expiracion,
             'negocio_id', n.id,
             'nombre_negocio', n.nombre_negocio,
             'disponible', (co.estado = 'obtenido'
                            AND (c.fecha_expiracion IS NULL OR c.fecha_expiracion >= now())
                            AND n.estado = 'activo'
                            AND n.fecha_vencimiento_suscripcion > now())
           )
           ORDER BY (co.estado = 'usado'), co.fecha_obtenido DESC
         ), '[]'::jsonb)
  INTO v_cupones
  FROM cupon_obtenido co
  JOIN cupon c ON c.id = co.cupon_id
  JOIN negocio n ON n.id = c.negocio_id
  WHERE co.usuario_id = v_uid;

  RETURN jsonb_build_object('exito', true, 'cupones', v_cupones);
END;
$function$;

comment on function public.mis_cupones_obtenidos() is
    'Cupones del usuario que llama (obtenidos y usados) con los datos del cupón y del negocio ya unidos. Sin tokens (027).';

-- -----------------------------------------------------------------------------
-- 6. iniciar_canje_cupon(p_token_negocio)
-- -----------------------------------------------------------------------------
create or replace function public.iniciar_canje_cupon(p_token_negocio text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
DECLARE
  v_n record;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Necesitas iniciar sesión.');
  END IF;

  SELECT n.id, n.nombre_negocio, n.estado, n.fecha_vencimiento_suscripcion
  INTO v_n
  FROM negocio_token_canje t
  JOIN negocio n ON n.id = t.negocio_id
  WHERE t.token = p_token_negocio;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Código de canje no válido.');
  END IF;

  IF v_n.estado <> 'activo' OR v_n.fecha_vencimiento_suscripcion IS NULL OR v_n.fecha_vencimiento_suscripcion <= now() THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Este negocio ya no está participando en la ruta.');
  END IF;

  RETURN jsonb_build_object('exito', true, 'negocio_id', v_n.id, 'nombre_negocio', v_n.nombre_negocio);
END;
$function$;

comment on function public.iniciar_canje_cupon(text) is
    'Valida el QR de canje de un negocio y devuelve negocio_id y nombre para mostrar los cupones del turista en ese negocio (027).';

-- -----------------------------------------------------------------------------
-- 7. usar_cupon(p_cupon_obtenido_id, p_token_negocio)
--    No mira cupon.activo: desactivar un cupón frena que se obtenga, no que lo use quien ya lo tiene.
--    Sí mira el vencimiento: un cupón vencido no se puede usar.
-- -----------------------------------------------------------------------------
create or replace function public.usar_cupon(p_cupon_obtenido_id bigint, p_token_negocio text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
DECLARE
  v_uid uuid := auth.uid();
  v_n record;
  v_co cupon_obtenido;
  v_c cupon;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Necesitas iniciar sesión.');
  END IF;

  SELECT n.id, n.nombre_negocio, n.estado, n.fecha_vencimiento_suscripcion
  INTO v_n
  FROM negocio_token_canje t
  JOIN negocio n ON n.id = t.negocio_id
  WHERE t.token = p_token_negocio;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Código de canje no válido.');
  END IF;

  IF v_n.estado <> 'activo' OR v_n.fecha_vencimiento_suscripcion IS NULL OR v_n.fecha_vencimiento_suscripcion <= now() THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Este negocio ya no está participando en la ruta.');
  END IF;

  -- La fila debe ser del usuario que llama (si no, no se revela que existe).
  SELECT * INTO v_co FROM cupon_obtenido
  WHERE id = p_cupon_obtenido_id AND usuario_id = v_uid
  FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Cupón no encontrado.');
  END IF;

  IF v_co.estado = 'usado' THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Este cupón ya fue usado.');
  END IF;

  SELECT * INTO v_c FROM cupon WHERE id = v_co.cupon_id;

  -- Defensa extra: solo en el negocio que lo emitió.
  IF v_c.negocio_id <> v_n.id THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Este cupón no se puede usar en este negocio.');
  END IF;

  IF v_c.fecha_expiracion IS NOT NULL AND v_c.fecha_expiracion < now() THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'Este cupón ya venció.');
  END IF;

  UPDATE cupon_obtenido SET estado = 'usado', fecha_uso = now() WHERE id = v_co.id;

  RETURN jsonb_build_object(
    'exito', true,
    'mensaje', '¡Cupón canjeado!',
    'descripcion', v_c.descripcion,
    'descuento_porcentaje', v_c.descuento_porcentaje,
    'nombre_negocio', v_n.nombre_negocio
  );
END;
$function$;

comment on function public.usar_cupon(bigint, text) is
    'El turista usa su cupón en el negocio que lo emitió, con el token del QR de canje. Valida dueño de la fila, estado, negocio y vencimiento (027).';

-- -----------------------------------------------------------------------------
-- 8. mis_cupones_otorgados(p_negocio_id)
-- -----------------------------------------------------------------------------
create or replace function public.mis_cupones_otorgados(p_negocio_id integer)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
DECLARE
  v_otorgados jsonb;
BEGIN
  IF NOT public.es_duenio_negocio(p_negocio_id) THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'No tienes permiso sobre este negocio.', 'cupones', '[]'::jsonb);
  END IF;

  SELECT coalesce(jsonb_agg(
           jsonb_build_object(
             'id', co.id,
             'cupon_id', c.id,
             'descripcion', c.descripcion,
             'descuento_porcentaje', c.descuento_porcentaje,
             'turista', coalesce(u.nombre_usuario, 'Turista'),
             'estado', co.estado,
             'fecha_obtenido', co.fecha_obtenido,
             'fecha_uso', co.fecha_uso
           )
           ORDER BY co.fecha_obtenido DESC
         ), '[]'::jsonb)
  INTO v_otorgados
  FROM cupon c
  JOIN cupon_obtenido co ON co.cupon_id = c.id
  JOIN usuario u ON u.id = co.usuario_id
  WHERE c.negocio_id = p_negocio_id;

  RETURN jsonb_build_object('exito', true, 'cupones', v_otorgados);
END;
$function$;

comment on function public.mis_cupones_otorgados(integer) is
    'Para el dueño: quién tiene cada cupón de su negocio (nombre_usuario) y si ya lo usó. El join con usuario lo hace la función (027).';

-- -----------------------------------------------------------------------------
-- 9. (extra) mis_cupones_negocio(p_negocio_id): el dueño obtiene los tokens para sus QR
-- -----------------------------------------------------------------------------
create or replace function public.mis_cupones_negocio(p_negocio_id integer)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
DECLARE
  v_cupones jsonb;
  v_token_canje text;
BEGIN
  IF NOT public.es_duenio_negocio(p_negocio_id) THEN
    RETURN jsonb_build_object('exito', false, 'mensaje', 'No tienes permiso sobre este negocio.', 'cupones', '[]'::jsonb);
  END IF;

  SELECT token INTO v_token_canje FROM negocio_token_canje WHERE negocio_id = p_negocio_id;

  SELECT coalesce(jsonb_agg(
           jsonb_build_object(
             'id', c.id,
             'token', c.token,
             'descripcion', c.descripcion,
             'descuento_porcentaje', c.descuento_porcentaje,
             'fecha_expiracion', c.fecha_expiracion,
             'limite_total', c.limite_total,
             'activo', c.activo,
             'fecha_creacion', c.fecha_creacion,
             'obtenidos', (SELECT count(*) FROM cupon_obtenido co WHERE co.cupon_id = c.id),
             'usados', (SELECT count(*) FROM cupon_obtenido co WHERE co.cupon_id = c.id AND co.estado = 'usado')
           )
           ORDER BY c.fecha_creacion DESC
         ), '[]'::jsonb)
  INTO v_cupones
  FROM cupon c
  WHERE c.negocio_id = p_negocio_id;

  -- token_canje es NULL hasta que el negocio crea su primer cupón.
  RETURN jsonb_build_object('exito', true, 'token_canje', v_token_canje, 'cupones', v_cupones);
END;
$function$;

comment on function public.mis_cupones_negocio(integer) is
    'Para el dueño: sus cupones con el token de cada QR, conteos de obtenidos/usados y el token de canje del negocio (027).';

-- -----------------------------------------------------------------------------
-- 10. Permisos de las funciones: solo con sesión (anon no tiene nada que hacer aquí)
-- -----------------------------------------------------------------------------
revoke execute on function public.obtener_cupon(text) from public, anon;
revoke execute on function public.mis_cupones_obtenidos() from public, anon;
revoke execute on function public.iniciar_canje_cupon(text) from public, anon;
revoke execute on function public.usar_cupon(bigint, text) from public, anon;
revoke execute on function public.mis_cupones_otorgados(integer) from public, anon;
revoke execute on function public.mis_cupones_negocio(integer) from public, anon;

grant execute on function public.obtener_cupon(text) to authenticated, service_role;
grant execute on function public.mis_cupones_obtenidos() to authenticated, service_role;
grant execute on function public.iniciar_canje_cupon(text) to authenticated, service_role;
grant execute on function public.usar_cupon(bigint, text) to authenticated, service_role;
grant execute on function public.mis_cupones_otorgados(integer) to authenticated, service_role;
grant execute on function public.mis_cupones_negocio(integer) to authenticated, service_role;

commit;
